-- Only starter IDs from migration 012; original user posts and all engagement are untouched.
begin;
alter table public.posts drop constraint if exists post_image_valid;
alter table public.posts add constraint post_image_valid check(image = '' or image ~* '^https?://' or image ~* '^data:image/(png|jpeg|webp|gif);base64,' or image ~ '^/learning-assets/[a-z0-9-]+\.svg$');
with editorial(author_id,n,topic,caption,image) as (values
('928eec0f-28d6-43fd-a075-2ebbad89c6c1'::uuid,1,'Study skills','Tried closing my notes and explaining the idea out loud. I thought I knew it until I got to the example. Going back to that part now.',''),
('928eec0f-28d6-43fd-a075-2ebbad89c6c1'::uuid,2,'Study skills','Small study win: finished one focused session without opening another tab. Keeping the next task small enough to actually start.',''),
('928eec0f-28d6-43fd-a075-2ebbad89c6c1'::uuid,3,'Study skills','How do you decide what belongs in a notebook? I keep copying too much. Trying a question, a short explanation and one example per page.',''),
('928eec0f-28d6-43fd-a075-2ebbad89c6c1'::uuid,4,'Study skills','Made a quiz from the things I got wrong instead of rereading the whole chapter. Much easier to tell what still needs practice.',''),
('928eec0f-28d6-43fd-a075-2ebbad89c6c1'::uuid,5,'Study skills','Study plan for tonight: 20 minutes learning, then explain it to someone. If my explanation gets confusing, that is the part I need to review.',''),
('300fab3a-e263-46eb-9cb6-3c4e85e43720'::uuid,1,'Programming','Full-stack lesson today: the button can look finished while the data still is not saved. I am checking everything again after a refresh now.',''),
('300fab3a-e263-46eb-9cb6-3c4e85e43720'::uuid,2,'Programming','Building a small score tracker for football practice. First version only needs a player name, attempts and goals. Trying not to add a dashboard before the basics work.',''),
('300fab3a-e263-46eb-9cb6-3c4e85e43720'::uuid,3,'Programming','Finally understood why React list keys matter when deleting an item. A stable ID follows the item; the array position can change.',''),
('300fab3a-e263-46eb-9cb6-3c4e85e43720'::uuid,4,'Programming','Anyone have a simple way to explain async/await to a beginner? My current explanation is “wait for the result without freezing the whole page”.',''),
('300fab3a-e263-46eb-9cb6-3c4e85e43720'::uuid,5,'Programming','Today was mostly debugging. One request was failing and I kept changing the UI. Reading the response message first would have saved time.',''),
('4b47db7c-af1e-4488-9535-c23cee34044b'::uuid,1,'Science','Why can we hear a neighbour through a wall? Sound is a vibration travelling through matter. Air is one route; a solid wall can carry vibrations too.',''),
('4b47db7c-af1e-4488-9535-c23cee34044b'::uuid,2,'Science','A vacuum is not a quiet kind of air. It is the absence of matter, so ordinary sound has no medium to travel through. Light is different.',''),
('4b47db7c-af1e-4488-9535-c23cee34044b'::uuid,3,'Science','Try explaining inertia using a bus that brakes. Your body keeps moving until another force changes its motion. The seat belt provides that force.',''),
('4b47db7c-af1e-4488-9535-c23cee34044b'::uuid,4,'Science','History question for the notebook: when two sources disagree, what was each writer able to observe? A date alone does not tell us how reliable a claim is.',''),
('4b47db7c-af1e-4488-9535-c23cee34044b'::uuid,5,'Science','One useful distinction: mass describes how much matter an object has; weight is a gravitational force. Moving to the Moon changes one much more than the other.',''),
('ef717f18-5802-4121-b4cd-d14d714302cc'::uuid,1,'Gardening','I am trying a soil check before watering instead of following a fixed weekday. The pot by the sunny window dries much faster than the one across the room.',''),
('ef717f18-5802-4121-b4cd-d14d714302cc'::uuid,2,'Gardening','Plant notebook update: light, soil moisture, and new growth go on separate lines. It is much easier to spot a pattern than with a vague “looks sad” note.','/learning-assets/plant-journal.svg'),
('ef717f18-5802-4121-b4cd-d14d714302cc'::uuid,3,'Gardening','A drainage hole helps excess water leave the pot, but the potting mix matters too. Still learning which mix suits each plant rather than using the same one for everything.',''),
('ef717f18-5802-4121-b4cd-d14d714302cc'::uuid,4,'Gardening','Native does not mean no care. I am checking which plants belong to our local area and what conditions they actually need before choosing the next one.',''),
('ef717f18-5802-4121-b4cd-d14d714302cc'::uuid,5,'Gardening','Noticed the new leaves facing the window. Rotating the pot a little at a time makes the growth easier to observe. Anyone keeping a weekly plant journal?',''),
('947e6e09-83f2-4c0c-a194-fd4e7fa40f20'::uuid,1,'Sewing','I finally made a test seam on a scrap before touching the project fabric. Two minutes of testing saved a whole evening of unpicking.',''),
('947e6e09-83f2-4c0c-a194-fd4e7fa40f20'::uuid,2,'Sewing','The seam allowance is part of the pattern, not spare fabric to guess at. Marking the guide on my machine helped my stitches stay much straighter.',''),
('947e6e09-83f2-4c0c-a194-fd4e7fa40f20'::uuid,3,'Sewing','Pressed each seam as I went today. The finished corner looks cleaner even though I did not change the stitching. Small step, big difference.',''),
('947e6e09-83f2-4c0c-a194-fd4e7fa40f20'::uuid,4,'Sewing','Question: what is your favourite way to transfer a pattern mark onto dark fabric? Testing every pen on a scrap first after my last experiment.',''),
('947e6e09-83f2-4c0c-a194-fd4e7fa40f20'::uuid,5,'Sewing','Learning to slow down at curves. Needle down, lift the foot, turn a little, then keep going. Not perfect yet, but no more sharp accidental corners.',''),
('9eb62eec-934e-400a-b958-53076ee9fef6'::uuid,1,'Programming','Before adding another library, try building the smallest version with what you already have. A working filter and an honest empty state beat five unfinished features.',''),
('9eb62eec-934e-400a-b958-53076ee9fef6'::uuid,2,'Programming','This is my tiny array filter example. filter returns a new array; it does not remove items from the original. Useful when rendering a search result in React.','/learning-assets/array-filter.svg'),
('9eb62eec-934e-400a-b958-53076ee9fef6'::uuid,3,'Programming','A blank page is not always a routing problem. Check the first console error, fix that one, then reload. The ten errors after it can be the same failure cascading.',''),
('9eb62eec-934e-400a-b958-53076ee9fef6'::uuid,4,'Programming','Project exercise: build a reading list with add, edit and delete. Then refresh the page. If everything disappears, persistence is your next lesson.',''),
('9eb62eec-934e-400a-b958-53076ee9fef6'::uuid,5,'Programming','Code review habit worth practicing: read the error path too. What does the user see when a save fails? A spinner that never stops is not an answer.',''),
('d6e773ba-40a9-4889-8e46-8d3f95e0ac6f'::uuid,1,'Traveling','Planning one neighbourhood per afternoon instead of crossing the whole city three times. Less transit, more time to actually notice the place.',''),
('d6e773ba-40a9-4889-8e46-8d3f95e0ac6f'::uuid,2,'Traveling','My planning sheet has three columns now: fixed bookings, flexible ideas, and a backup for rain. The backup column saved me a lot of last-minute scrolling.','/learning-assets/travel-plan.svg'),
('d6e773ba-40a9-4889-8e46-8d3f95e0ac6f'::uuid,3,'Traveling','Learning a few polite phrases before a trip makes ordinary interactions easier. Today I am practicing how to ask someone to repeat something slowly.',''),
('d6e773ba-40a9-4889-8e46-8d3f95e0ac6f'::uuid,4,'Traveling','Offline maps are useful, but I also save the address of where I am staying as plain text. Nice to have something readable when a map will not load.',''),
('d6e773ba-40a9-4889-8e46-8d3f95e0ac6f'::uuid,5,'Traveling','Budget lesson from planning: separate the transport between cities from transport inside each city. I used to forget the second part completely.',''),
('6b3620e1-a20f-4014-97b0-ea5406b7d984'::uuid,1,'Baking','My muffins used to come out a bit tough. I stopped mixing as soon as the dry flour disappeared today. A few lumps really are okay.',''),
('6b3620e1-a20f-4014-97b0-ea5406b7d984'::uuid,2,'Baking','Keeping this little baking checklist beside the scales. Weigh first, preheat, then mix. Much calmer than hunting for ingredients with batter already in the bowl.','/learning-assets/baking-prep.svg'),
('6b3620e1-a20f-4014-97b0-ea5406b7d984'::uuid,3,'Baking','Butter was too cold for creaming again 😅 Cutting it into smaller pieces helped it soften more evenly. Soft enough to press, not melted.',''),
('6b3620e1-a20f-4014-97b0-ea5406b7d984'::uuid,4,'Baking','Question for the bread people: what do you look for when deciding the dough has risen enough? I am trying to watch the dough instead of only the clock.',''),
('6b3620e1-a20f-4014-97b0-ea5406b7d984'::uuid,5,'Baking','The first tray spread much more than the second. Same dough, but the second tray had time in the fridge. Writing down the difference so I can repeat it.',''),
('9ba52775-eb20-4121-a5c4-db84f3bda407'::uuid,1,'Art & Design','I keep reaching for white when a colour looks too dark. Today I tried mixing a little of its complement instead. Much more interesting shadows, but easy to overdo it.',''),
('9ba52775-eb20-4121-a5c4-db84f3bda407'::uuid,2,'Art & Design','Three mixes from the same blue and orange. The middle one is finally close to the grey I wanted for a rainy sky. Keeping a swatch beside the canvas helps.','/learning-assets/colour-mixes.svg'),
('9ba52775-eb20-4121-a5c4-db84f3bda407'::uuid,3,'Art & Design','Anyone else spend longer cleaning the palette than actually painting? Small goal for tonight: one apple, three values, no tiny details.',''),
('9ba52775-eb20-4121-a5c4-db84f3bda407'::uuid,4,'Art & Design','Painted the background first this time. Leaving a clean silhouette made the mug much easier to place. Still working on the handle.',''),
('9ba52775-eb20-4121-a5c4-db84f3bda407'::uuid,5,'Art & Design','Tiny acrylic lesson: a thin layer dries before I finish blending a big area. Working in smaller sections is helping more than rushing.',''),
('b59a7542-3c42-40f8-8497-38476beac336'::uuid,1,'Mathematics','A common graph mistake: (-2)² is 4, not -4. Put the negative number in brackets before squaring. Try plotting -2, -1, 0, 1 and 2 to see the symmetry.',''),
('b59a7542-3c42-40f8-8497-38476beac336'::uuid,2,'Mathematics','Here is the little value table I use before drawing y = x². The points on either side of zero give the same height. Can you explain why?','/learning-assets/quadratic.svg'),
('b59a7542-3c42-40f8-8497-38476beac336'::uuid,3,'Mathematics','Quick mental challenge: 15% of 80. Find 10% first, then half of that for 5%. Add the two pieces. What answer do you get?',''),
('b59a7542-3c42-40f8-8497-38476beac336'::uuid,4,'Mathematics','If you can solve an equation but cannot explain the next step, slow down and name the operation. We are keeping both sides equal, not just moving symbols.',''),
('b59a7542-3c42-40f8-8497-38476beac336'::uuid,5,'Mathematics','Today’s exit question: does a bigger denominator always mean a bigger fraction? Compare 1/3 and 1/8 before answering.',''),
('8ba423f3-36a0-4b2a-b2c3-cf866823136a'::uuid,1,'Technology','Checking the app from a smaller screen today. A button that is easy with a mouse can be surprisingly awkward with a thumb.',''),
('8ba423f3-36a0-4b2a-b2c3-cf866823136a'::uuid,2,'Technology','My testing checklist: create something, edit it, refresh, then find it again. Happy-path clicks alone missed several issues.',''),
('8ba423f3-36a0-4b2a-b2c3-cf866823136a'::uuid,3,'Technology','An empty list should explain what goes there and how to add the first item. “No data” tells me almost nothing.',''),
('8ba423f3-36a0-4b2a-b2c3-cf866823136a'::uuid,4,'Technology','Testing videos taught me that an MP4 filename is not the whole story. The browser also has to support the codec inside the file.',''),
('8ba423f3-36a0-4b2a-b2c3-cf866823136a'::uuid,5,'Technology','Working through the learning flow from a new user’s perspective. The next action should be obvious without someone standing beside the screen.',''),
('0f6f7809-90ba-483a-8e05-bddcdae52e1a'::uuid,1,'Programming','I have the layout working. Next challenge is keeping the form values when something fails instead of making the user start again.',''),
('0f6f7809-90ba-483a-8e05-bddcdae52e1a'::uuid,2,'Programming','CSS reminder to myself: check the parent width before changing the child for the tenth time.',''),
('0f6f7809-90ba-483a-8e05-bddcdae52e1a'::uuid,3,'Programming','Built a search filter today. Added a separate empty state for no matches so it does not look like the page failed to load.',''),
('0f6f7809-90ba-483a-8e05-bddcdae52e1a'::uuid,4,'Programming','Trying to make commit messages describe the change instead of just “fix”. Future me deserves a clue.',''),
('0f6f7809-90ba-483a-8e05-bddcdae52e1a'::uuid,5,'Programming','Pair debugging helped today. Explaining what I expected the code to do made the missing condition obvious.','')
)
update public.posts p set topic=e.topic,caption=e.caption,image=e.image
from editorial e where p.id=md5('btb-starter-20260930-'||e.author_id::text||'-'||e.n)::uuid
and p.author_id=e.author_id and p.kind='post'
and (p.caption like '%A small idea worth keeping in your notes.' or p.caption like '%Try explaining this in your own words.' or p.caption like '%What is your favorite example of this?' or p.caption like '%One topic, one useful takeaway.' or p.caption like '%What would you add to this?');
commit;
